version: '3.3'
services:
  notify-nosql-db:
    image: mongo
    restart: always
    volumes:
      - notify-nosql-db-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/notify-nosql-db-user
#      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/notify-nosql-db-password
#    secrets:
#      - notify-nosql-db-user
#      - notify-nosql-db-password
  notify-nosql-db-dev-gui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: notify-nosql-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
networks:
  default:
    driver: overlay
volumes:
  notify-nosql-db-volume:
    driver: local
#secrets:
#  notify-nosql-db-user:
#    external: true
#  notify-nosql-db-password:
#    external: true
